catch non-existant binary

diff --git a/sbin/nsl b/sbin/nsl
--- a/sbin/nsl
+++ b/sbin/nsl
@@ -1,1 +1,11 @@
+#!/bin/bash
+# uses https://github.com/thetanz/golang-nslookup
+
+# check lookup is in path
+if ! which lookup > /dev/null; then
+  echo "lookup not found in path"
+  echo "go checkout https://github.com/thetanz/golang-nslookup/releases"
+  exit 1
+fi
+
 lookup $@ | jq
